- name: Ensure directories is exist
  ansible.builtin.file:
    path: /opt/gopher-pinger/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - ""
    - "nginx"

- name: Create configs
  ansible.builtin.template:
    src: "templates/{{ item.src }}"
    dest: "/opt/gopher-pinger/{{ item.dest }}"
    mode: '0644'
  notify: Restart Containers
  loop:
    - { src: 'conf.d.j2', dest: 'nginx/default.conf'}
    - { src: 'promtail-config.j2', dest: 'promtail-config.yaml'}
    - { src: 'docker-compose.j2', dest: 'docker-compose.yml'}

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start app
  community.docker.docker_compose_v2:
    project_src: /opt/gopher-pinger
    pull: always
    state: present
  register: output

- name: Verify that nginx and up services are running
  ansible.builtin.assert:
    that:
      - nginx_container.State == 'running'
      - go_container.State == 'running'
  vars:
    nginx_container: "{{ output.containers | selectattr('Service', 'equalto', 'nginx') | first }}"
    go_container: "{{ output.containers | selectattr('Service', 'equalto', 'go') | first }}"
