// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PingerMetrics is an autogenerated mock type for the PingerMetrics type
type PingerMetrics struct {
	mock.Mock
}

// DecWorker provides a mock function with no fields
func (_m *PingerMetrics) DecWorker() {
	_m.Called()
}

// IncWorker provides a mock function with no fields
func (_m *PingerMetrics) IncWorker() {
	_m.Called()
}

// NewPing provides a mock function with given fields: URL, status, duration
func (_m *PingerMetrics) NewPing(URL string, status int, duration time.Duration) {
	_m.Called(URL, status, duration)
}

// NewRequest provides a mock function with given fields: method, status, duration
func (_m *PingerMetrics) NewRequest(method string, status int, duration time.Duration) {
	_m.Called(method, status, duration)
}

// NewPingerMetrics creates a new instance of PingerMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingerMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingerMetrics {
	mock := &PingerMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
