// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Zapi-web/gopher-pinger/internal/domain"
	mock "github.com/stretchr/testify/mock"

	ulid "github.com/oklog/ulid/v2"
)

// PingerService is an autogenerated mock type for the PingerService type
type PingerService struct {
	mock.Mock
}

// DeleteProcess provides a mock function with given fields: ctx, id
func (_m *PingerService) DeleteProcess(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProcess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProcess provides a mock function with given fields: ctx, id
func (_m *PingerService) GetProcess(ctx context.Context, id string) (domain.Target, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProcess")
	}

	var r0 domain.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Target, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Target); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Target)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with no fields
func (_m *PingerService) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResultsMonitoring provides a mock function with no fields
func (_m *PingerService) ResultsMonitoring() {
	_m.Called()
}

// StartMonitoring provides a mock function with given fields: ctx, url, interval
func (_m *PingerService) StartMonitoring(ctx context.Context, url string, interval int) (ulid.ULID, error) {
	ret := _m.Called(ctx, url, interval)

	if len(ret) == 0 {
		panic("no return value specified for StartMonitoring")
	}

	var r0 ulid.ULID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (ulid.ULID, error)); ok {
		return rf(ctx, url, interval)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ulid.ULID); ok {
		r0 = rf(ctx, url, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ulid.ULID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, url, interval)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProcess provides a mock function with given fields: ctx, id, interval
func (_m *PingerService) UpdateProcess(ctx context.Context, id string, interval int) error {
	ret := _m.Called(ctx, id, interval)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, id, interval)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPingerService creates a new instance of PingerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingerService {
	mock := &PingerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
