// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ulid "github.com/oklog/ulid/v2"
)

// ProcessStore is an autogenerated mock type for the ProcessStore type
type ProcessStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *ProcessStore) Delete(key ulid.ULID) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ulid.ULID) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *ProcessStore) Get(key ulid.ULID) (context.CancelFunc, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 context.CancelFunc
	var r1 error
	if rf, ok := ret.Get(0).(func(ulid.ULID) (context.CancelFunc, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(ulid.ULID) context.CancelFunc); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.CancelFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(ulid.ULID) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, value
func (_m *ProcessStore) Set(key ulid.ULID, value context.CancelFunc) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ulid.ULID, context.CancelFunc) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProcessStore creates a new instance of ProcessStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessStore {
	mock := &ProcessStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
