name: Main Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    go-tests:
        uses: ./.github/workflows/go.yml
    tf-linting:
        uses: ./.github/workflows/terraform.yml